// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SyncServer
{

using global::System;
using global::FlatBuffers;

public struct AbortPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AbortPacket GetRootAsAbortPacket(ByteBuffer _bb) { return GetRootAsAbortPacket(_bb, new AbortPacket()); }
  public static AbortPacket GetRootAsAbortPacket(ByteBuffer _bb, AbortPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AbortPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short Opcode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }

  public static Offset<AbortPacket> CreateAbortPacket(FlatBufferBuilder builder,
      short opcode = 0) {
    builder.StartObject(1);
    AbortPacket.AddOpcode(builder, opcode);
    return AbortPacket.EndAbortPacket(builder);
  }

  public static void StartAbortPacket(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddOpcode(FlatBufferBuilder builder, short opcode) { builder.AddShort(0, opcode, 0); }
  public static Offset<AbortPacket> EndAbortPacket(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AbortPacket>(o);
  }
};


}
