// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SyncServer
{

using global::System;
using global::FlatBuffers;

public struct KeepAlivePacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static KeepAlivePacket GetRootAsKeepAlivePacket(ByteBuffer _bb) { return GetRootAsKeepAlivePacket(_bb, new KeepAlivePacket()); }
  public static KeepAlivePacket GetRootAsKeepAlivePacket(ByteBuffer _bb, KeepAlivePacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public KeepAlivePacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short Opcode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public bool Success { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<KeepAlivePacket> CreateKeepAlivePacket(FlatBufferBuilder builder,
      short opcode = 0,
      bool success = false) {
    builder.StartObject(2);
    KeepAlivePacket.AddOpcode(builder, opcode);
    KeepAlivePacket.AddSuccess(builder, success);
    return KeepAlivePacket.EndKeepAlivePacket(builder);
  }

  public static void StartKeepAlivePacket(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddOpcode(FlatBufferBuilder builder, short opcode) { builder.AddShort(0, opcode, 0); }
  public static void AddSuccess(FlatBufferBuilder builder, bool success) { builder.AddBool(1, success, false); }
  public static Offset<KeepAlivePacket> EndKeepAlivePacket(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<KeepAlivePacket>(o);
  }
};


}
