// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SyncServer
{

using global::System;
using global::FlatBuffers;

public struct PlayerData : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public PlayerData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long UserId { get { return __p.bb.GetLong(__p.bb_pos + 0); } }
  public float PosX { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }
  public float PosY { get { return __p.bb.GetFloat(__p.bb_pos + 12); } }
  public bool Active { get { return 0!=__p.bb.Get(__p.bb_pos + 16); } }

  public static Offset<PlayerData> CreatePlayerData(FlatBufferBuilder builder, long UserId, float PosX, float PosY, bool Active) {
    builder.Prep(8, 24);
    builder.Pad(7);
    builder.PutBool(Active);
    builder.PutFloat(PosY);
    builder.PutFloat(PosX);
    builder.PutLong(UserId);
    return new Offset<PlayerData>(builder.Offset);
  }
};


}
